### ISSUE TITLE
lua error when using fstack ctrl-c

### ISSUE THREAD

**Issue by mooreatv** [Stanzilla/WoWUIBugs#16]
With 0 addons:

/fstack

mouse over any texture, use shift to see texture,
hit Ctrl-C

```
Message: ...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:587: Usage: CopyToClipboard("string" [, removeMarkup])
Time: Wed Jul 10 14:34:27 2019
Count: 1
Stack: ...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:587: Usage: CopyToClipboard("string" [, removeMarkup])
[C]: in function `CopyToClipboard'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:587: in function `FrameStackTooltip_HandleFrameCommand'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:557: in function `command'
Interface\SharedXML\KeyCommand.lua:46: in function `Update'
Interface\SharedXML\KeyCommand.lua:110: in function `KeyCommand_Update'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:791: in function <...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:790>

Locals: (*temporary) = MultiBarBottomRightButton9Icon {
 0 = <userdata>
}
```

**Comment by Ketho** [comment]
It looks like it complains on any table values since it (unsurprisingly) only accepts strings
https://www.townlong-yak.com/framexml/live/Blizzard_DebugTools/Blizzard_DebugTools.lua#577

On another note, only the last asset would be effectively copied to the clipboard. While it intentionally breaks the loop on Atlases / [HandleAtlasMemberCommand()](https://wow.gamepedia.com/API_HandleAtlasMemberCommand) of which I have no idea what it's doing

![image](https://user-images.githubusercontent.com/1073877/61759827-b6e4f200-adc9-11e9-8160-4683ed454e66.png)

**Comment by Meorawr** [comment]
GetTextureFilePath as of 9.0.1 no longer seems to return `self` when assigned a texture via file ID or atlas.

**Comment by Ketho** [comment]
Not sure if what Meorawr referred to was what fixed it, but I can't reproduce the error anymore.
