### ISSUE TITLE
ints between 2 and 4B (ie with bit 31 set) can't be passed to string.format %u or %x

### ISSUE THREAD

**Issue by mooreatv** [Stanzilla/WoWUIBugs#19]
string.format("%u", bit.bnot(0))

integer overflow attempting to store 4294967295

same with %x etc
(works on regular lua 5.1 as well as C obviously)

**Comment by Stanzilla** [comment]
Needs more details

**Comment by Meorawr** [comment]
The "integer overflow" error is definitely something of their own making - the stock 5.1 VM doesn't have that message whatsoever for anything. Some of this might have platform-specific quirks, so I'll preface this by saying it was tested on a 64-bit Windows 10 system.

Inside the game, all values supplied into all `bit.*` functions appear to (sensibly) be normalized by taking the value of their least-significant 32 bits. Their results are constrained to the range of *unsigned* 32-bit integers - though of course represented as lua_Numbers (doubles) by the VM.

```lua
print(bit.bor(2^8 - 1, 0))  -- prints: 255
print(bit.bor(2^16 - 1, 0)) -- prints: 65535
print(bit.bor(2^24 - 1, 0)) -- prints: 16777215
print(bit.bor(2^31 - 1, 0)) -- prints: 2147483647
print(bit.bor(2^32 - 1, 0)) -- prints: 4294967295 (0xffffffff)
print(bit.bor(2^48 - 1, 0)) -- prints: 4294967295
print(bit.bor(2^51 - 1, 0)) -- prints: 4294967295
print(bit.bor(2^52 - 1, 0)) -- prints: 4294967295
print(bit.bor(2^53 - 1, 0)) -- prints: 4294967295
```

The returns being unsigned is a bit of an oddity since people may assume the semantics used by the bitop (<http://bitop.luajit.org/semantics.html>) library which actually returns values in the range of *signed* 32-bit numbers, which is likely what everyone else who's tested this out-of-game has compared against.

Running that same test _outside of the game_ results with the aforementioned library in the following, just for reference:

```lua
print(bit.bor(2^8 - 1, 0))  -- prints: 255
print(bit.bor(2^16 - 1, 0)) -- prints: 65535
print(bit.bor(2^24 - 1, 0)) -- prints: 16777215
print(bit.bor(2^31 - 1, 0)) -- prints: 2147483647
print(bit.bor(2^32 - 1, 0)) -- prints: -1
print(bit.bor(2^48 - 1, 0)) -- prints: -1
print(bit.bor(2^51 - 1, 0)) -- prints: -1
print(bit.bor(2^52 - 1, 0)) -- prints: 0
print(bit.bor(2^53 - 1, 0)) -- prints: 0
```

The signedness of the input parameters doesn't matter for all functions except for `bit.arshift`, where the MSB of the input is propagated to the output as expected; all other functions return unsigned values as mentioned:

```lua
-- 4294967040 = 0xffffff00 = -256

assert(bit.band(-256, 0) == bit.band(4294967040, 0)) -- no error
assert(bit.bxor(-256, 0) == bit.bxor(4294967040, 0)) -- no error
assert(bit.bor(-256, 0) == bit.bor(4294967040, 0)) -- no error
assert(bit.bnot(-256) == bit.bnot(4294967040)) -- no error
assert(bit.lshift(-256, 1) == bit.lshift(4294967040, 1)) -- no error
assert(bit.rshift(-256, 1) == bit.rshift(4294967040, 1)) -- no error
assert(bit.arshift(-256, 0) == bit.arshift(4294967040, 0)) -- no error

print(bit.arshift(4294967040, 0) == -256) -- prints: true
```

The issue is that for whatever reason, pumping any unsigned number above 2^31 - 1 through `string.format` with any of the `%d`, `%i`, `%u`, `%x`, `%X`, or `%o` specifiers triggers an error.

```lua
print(pcall(string.format, "%d", 2^31))     -- prints: integer overflow attempting to store 2147483648
print(pcall(string.format, "%d", 2^31 - 1)) -- prints: 2147483647
print(pcall(string.format, "%i", 2^31))     -- prints: integer overflow attempting to store 2147483648
print(pcall(string.format, "%i", 2^31 - 1)) -- prints: 2147483647
print(pcall(string.format, "%u", 2^31))     -- prints: integer overflow attempting to store 2147483648
print(pcall(string.format, "%u", 2^31 - 1)) -- prints: 2147483647
print(pcall(string.format, "%x", 2^31))     -- prints: integer overflow attempting to store 2147483648
print(pcall(string.format, "%x", 2^31 - 1)) -- prints: 7fffffff
print(pcall(string.format, "%X", 2^31))     -- prints: integer overflow attempting to store 2147483648
print(pcall(string.format, "%X", 2^31 - 1)) -- prints: 7FFFFFFF
print(pcall(string.format, "%o", 2^31))     -- prints: integer overflow attempting to store 2147483648
print(pcall(string.format, "%o", 2^31 - 1)) -- prints: 17777777777
```

One workaround addons can apply is to launder unsigned integers through `bit.arshift` which retains the bit pattern of its input - either signed or unsigned - and always returns a signed value. This lets you use the full 32-bit value range without any overflow errors.

```lua
print(pcall(string.format, "%d", bit.arshift(2^32, 0)))     -- prints: 0
print(pcall(string.format, "%d", bit.arshift(2^32 - 1, 0))) -- prints: -1
print(pcall(string.format, "%i", bit.arshift(2^32, 0)))     -- prints: 0
print(pcall(string.format, "%i", bit.arshift(2^32 - 1, 0))) -- prints: -1
print(pcall(string.format, "%u", bit.arshift(2^32, 0)))     -- prints: 0
print(pcall(string.format, "%u", bit.arshift(2^32 - 1, 0))) -- prints: 4294967295
print(pcall(string.format, "%x", bit.arshift(2^32, 0)))     -- prints: 0
print(pcall(string.format, "%x", bit.arshift(2^32 - 1, 0))) -- prints: ffffffff
print(pcall(string.format, "%X", bit.arshift(2^32, 0)))     -- prints: 0
print(pcall(string.format, "%X", bit.arshift(2^32 - 1, 0))) -- prints: FFFFFFFF
print(pcall(string.format, "%o", bit.arshift(2^32, 0)))     -- prints: 0
print(pcall(string.format, "%o", bit.arshift(2^32 - 1, 0))) -- prints: 37777777777
```

**Comment by mooreatv** [comment]
there is no undefined behavior, %u of 0xffffffff is perfectly valid and should just work

Lua 5.1.1  Copyright (C) 1994-2006 Lua.org, PUC-Rio
> print(string.format("%x", bit.bnot(0)))
ffffffff

no need to make it complicated

**Comment by mooreatv** [comment]
tostring() works fine (but isn't doing what %x does)

**Comment by Meorawr** [comment]
> 
> there is no undefined behavior, %u/%x of 0xffffffff is perfectly valid and should just work
> 

Didn't say that specific case was undefined.

> For cases where the input number **lies outside representable range** of the corrected types

It's [undefined behaviour](http://eel.is/c++draft/conv.fpint#1) if you're trying to format something _larger_ than 2^32 - 1 into what internally _may_ be defaulting to an `unsigned long` for the `%u`/`%x` specifiers. In that case them trapping and raising it as an error case is sensible and outright preferable since `unsigned long` additionally varies between platforms; no one will want to deal with Windows-specific `string.format` differences inside the game environment.

0xffffffff is within range and thus shouldn't be erroring; the client appears validating that all input numbers to `string.format` for all of `%d`/`%u`/`%x`/etc. are within the range of a _signed_ integral type even if the intent is for them to be formatted an an _unsigned_ one. Laundering such values through `bit.arshift(value, 0)` appears to help for Windows clients at least, allowing anything between 0x80000000 and 0xffffffff to be formatted correctly by appropriately signing the result.

**Comment by Meorawr** [comment]
Closing as this likely isn't a bug and probably won't be changed.
