### ISSUE TITLE
Create Release Branches for UI Source

### ISSUE THREAD

**Issue by ChrisKader** [Stanzilla/WoWUIBugs#197]
Since the "X.C.M Consolidated UI Changes" Wiki pages commonly contain links to source files for referenced functions, it would be beneficial to have a branch created within this repo with the respective release UI source. That way any links to source code will never be broken. This would also help with submitting UI issues as issues can reference links to source code that wont break.

**Comment by Stanzilla** [comment]
I added a `live` and `ptr` branch based on https://github.com/BigWigsMods/WoWUI/

**Comment by Ketho** [comment]
> That way any links to source code will never be broken.

The issue was mainly with linking to Townlong-Yak framexml builds. Linking to either Gethe or Funkeh their mirrors would already be a good enough solution imo.

**Comment by Meorawr** [comment]
Most links already do link to a UI export, the TL links are just for Blizzard-provided API documentation - something that, if broken, you can just look up yourself.

I avoid linking them to `/live/` explicitly because they won't work for the duration of the PTR, and will eventually break again if whatever is being documented specific to that patch is removed later on.

Odds are I'll just stop using TL links entirely going forward and point them to Gethe's repo, which now has branches for all products which massively simplifies things.

**Comment by ChrisKader** [comment]
Links to code issues can easily point to the state of the file when the issue is created and is even supported by GitHub. So even regardless of how the file changes, the issue will always point to the state in which the issue is referencing.

Chris Kader
________________________________

**Comment by Meorawr** [comment]
Right, but you can also just get permanent links to FrameXML source from another repo as has been done in many existing bug reports - see #185 for an example.

You don't get the inline preview of the source this way, but that's not a huge loss. The effort of setting up an automated UI export (which often has small issues requiring manual re-runs) for every product branch _here_ isn't worth it when it's already done elsewhere.

**Comment by ChrisKader** [comment]
1.  Having a repo that is dedicated to logging changes to UI source without the actual source (when the source is out by Aimable by anyone) is a bit counter productive.

  1.  Other repos can disappear at any point. Relying on another repo just because it’s “easier” is a problem waiting to happen.

Chris Kader
________________________________

**Comment by Meorawr** [comment]
If Gethe's repo ever magically disappears then a lot more things than just the consolidated change lists will have problems; wiki articles use it as a reference for FrameXML links in places, and it's essentially the "recommended" repo at this point. He's also not just going to delete the repository entirely without notice on a whim; worst realistic case it'd stop being maintained - which is unlikely as, to my knowledge, multiple people have write access - and even so all existing links would remain valid.

There's also been long term concerns over the searchability of the source exports on GitHub that additionally make using just one repository for all product branches undesirable; the code search tooling only indexes the main branch of a repo, which makes it extremely annoying to go through the source quickly when trying to report an issue that's only relevant to the export of Classic or BCC. That's only fixed by one repo per client source branch, which would lead to splitting the issue tracker per-client, and that's not at all desirable for any parties.

The change summaries themselves aren't intended to be living documents that meticulously cover every change, the purpose is to point out the important or otherwise interesting ones relevant for a patch to assist authors with updates typically **before** the full documentation for any such changes in a patch is merged into the proper wiki. Authors are expected to still do their own research and testing _beyond_ what's stated in the change summaries. If there's an error or broken link in them then they'll get fixed if someone reports it, but we don't need to overengineer a solution to prevent dead links in the first place. Additionally I don't want to use the GH wiki going forward for the change summaries; it was just a convenience when they first started - so having the source here won't help long term for those anyway.

For the case of links in issue reports it's also not that important for the same reasons. As long as there's clear instructions on how to reproduce an issue - either as a `/run` or as an attached test case - there's enough of a trail for the developers to investigate. Source links and walkthroughs help, but aren't critical - and in many cases FrameXML issues with all the above have a shelf life measured in weeks before being fixed and closed, at which point further maintenance of any links or content inside are irrelevant.

**Comment by Ketho** [comment]
> Additionally I don't want to use the GH wiki going forward for the change summaries; it was just a convenience when they first started

Does that mean you'll write any change summaries on Wowpedia? If you're not annoyed by the wikitext
