### ISSUE TITLE
GameTooltip:GetItem() returns incorrect item from the Toy Box collection

### ISSUE THREAD

**Issue by NielsHeltner** [Stanzilla/WoWUIBugs#25]
On a fresh login session, running `GameTooltip:GetItem()` while hovering over a toy in the toy box collection will return the toy you are hovering over. However, if during the login session you have hovered over any item in your bag or character pane, invoking `GameTooltip:GetItem()` while hovering over a toy in the toy box will return the item you last hovered over, and not the toy.

**Comment by Ketho** [comment]
I can confirm this issue, the gametooltip API is wonky.

e.g. after calling `GameTooltip:SetInventoryItem("player", INVSLOT_HEAD)` any further `GameTooltip:GetItem()` calls just return that item instead of any currently set toybox item from [GameTooltip:SetToyByItemID()](https://github.com/Gethe/wow-ui-source/blob/356d028f9d245f6e75dc8a806deb3c38aa0aa77f/AddOns/Blizzard_Collections/Blizzard_ToyBox.lua#L139)

**Comment by NielsHeltner** [comment]
Seems to have been fixed by Blizzard in 9.0.
