### ISSUE TITLE
bug in ActionButton_UpdateFlyout when using a type attribute that equals "flyout" with CheckButton's that inherits SecureActionButtonTemplate / ActionButtonTemplate. 

### ISSUE THREAD

**Issue by nightness** [Stanzilla/WoWUIBugs#27]
When Toggling the flyout for a secure action button, you will see this error...

FrameXML\ActionButton.lua:976: Usage: GetActionInfo(slot)
[string "=[C]"]: in function `GetActionInfo'
[string "@FrameXML\ActionButton.lua"]:976: in function `ActionButton_UpdateFlyout'
[string "@FrameXML\SpellFlyout.lua"]:396: in function <FrameXML\SpellFlyout.lua:383>
[string "=[C]"]: in function `Show'
[string "@FrameXML\SpellFlyout.lua"]:376: in function `Toggle'
[string "@FrameXML\SecureTemplates.lua"]:363: in function `handler'
[string "@FrameXML\SecureTemplates.lua"]:632: in function <FrameXML\SecureTemplates.lua:580>

I fixed it for Blizzard, but they need to implement it (else taint occurs)... https://pastebin.com/6q8kDrp0

**Comment by Nevcairiel** [comment]
The ActionButton_* class of functions is only designed to work with buttons of the type = "action"

If you want to use a secure action button with type = "flyout", you need to provide your own implementation for all action button functionality - which is certainly possible, since the flyout arrow and border are not protected frames. I've done it myself in LibActionButton-1.0
