### ISSUE TITLE
Mount Selection Scrolls Strange

### ISSUE THREAD

**Issue by kodewdle** [Stanzilla/WoWUIBugs#34]
**BETA ONLY**

Mount selection will stay centered as you try to select something which feels unnatural in my opinion. I don't know if this is a bug or intended but here is the report anyways!

Since I can't upload mp4 format on here, I've uploaded the clips to YouTube to demonstrate the problem:

Retail **(normal?)**: https://youtu.be/8l5WMiJIF5k
Beta **(strange?)**: https://youtu.be/uguz6ut3p8o

**Comment by Meorawr** [comment]
This is likely caused by the [HybridScrollFrame_ScrollToIndex](https://www.townlong-yak.com/framexml/30920/HybridScrollFrame.lua#262) function added in 8.2, which is now called by [MountJournal_SetSelected](https://www.townlong-yak.com/framexml/beta/Blizzard_Collections/Blizzard_MountCollection.lua#661) as of 9.0.1.

As far as I can tell it adjusting items to the centre of the view is intended, so it's probably likely we'll start seeing more of this behaviour going forward and that this is _likely_ intentional rather than a bug.

**Comment by kodewdle** [comment]
was fixed in beta
