### ISSUE TITLE
[Retail] IME Broke on tradeskill frame search bar

### ISSUE THREAD

**Issue by EKE00372** [Stanzilla/WoWUIBugs#428]
![專業bug](https://user-images.githubusercontent.com/1412472/236656505-e3f7c2f7-a7af-4cc9-9703-e4b310016c59.gif)

Demo: zhTW clinet and PIME input mode

Confirmed this issue happened universal on useing IME input in windows, including pinyin and bopomofo.

**Comment by CyanoHao** [comment]
zhCN Microsoft Pinyin:
![wow-zh](https://user-images.githubusercontent.com/14287996/236659393-0e138867-2795-42ea-824a-a70746296980.gif)

koKR Microsoft IME:
![wow-kr](https://user-images.githubusercontent.com/14287996/236659336-462a2bb5-8dbd-444c-8f20-a58426cfaaab.gif)

Expected behaviour:
![notepad-zh](https://user-images.githubusercontent.com/14287996/236659395-aa8b8843-6a3f-4e8d-aff6-d65a72815d23.gif)
![notepad-kr](https://user-images.githubusercontent.com/14287996/236659325-d2674bea-d02e-40ea-87a3-3e80c2079946.gif)

**Comment by EKE00372** [comment]
confrim issue still in 10.1.5.49595 PTR

**Comment by plusmouse** [comment]
This issue can be worked around with an addon that overrides the default behaviour of the search box:
Release: https://addons.wago.io/addons/fix-professions-view-search-box-for-ime-input
Source: https://github.com/plusmouse/FixIMEProfessionsView

**Comment by EKE00372** [comment]
Fixed in 10.2.7.54630
