### ISSUE TITLE
Add CanEditOfficerNote to Deprecated API Removals

### ISSUE THREAD

**Issue by dartraiden** [Stanzilla/WoWUIBugs#50]
[8.2.0] `CanEditOfficerNote` was relocated to the `C_GuildInfo` namespace.
[9.0.1] `CanEditOfficerNote` was removed

**Comment by Nevcairiel** [comment]
That doesn't sound like a UI bug to me.

**Comment by Meorawr** [comment]
[This is also already covered on that wiki page.](https://github.com/Stanzilla/WoWUIBugs/wiki/9.0.1-Consolidated-UI-Changes#820)

> Functions for querying the guild roster and officer notes were relocated to the C_GuildInfo namespace.

Each function that was deprecated/removed wasn't listed individually because there's:

1. Too many of them.
2. Not particularly relevant to 9.0.1 specifically; they've deprecated since their own respective patches for over a year now.
