### ISSUE TITLE
Per-character `AddOns.txt` files are occasionally duplicated across realms and are not kept in-sync

### ISSUE THREAD

**Issue by Ghostopheles** [Stanzilla/WoWUIBugs#608]
# The Issue
All characters* on your account, upon login to a realm, have a duplicate AddOns.txt file created under the realm the player is currently connected to. As a result, the addons API only reads the addon configuration from that realm's folder, even if the character actually lives on a completely different realm.

This leads to a fun situation where, if you're not connected to that character's native realm, you can change the character's addon 'loadout', then switch realms, check addons again, and see a completely different list, as the files are not kept in-sync between realms.

## SavedVariables too?
In my case, I actually found one or two characters that ended up with their entire character folder copied over to the other realm. SavedVariables, AddOns.txt, chat-cache.txt, and so on. It's unlikely that these other files would have any impact on the user experience, though.

There was at least one report of someone seeing characters from an entirely different game account in their realm folder as well, though I've been unable to reproduce that specific case.

# Repro
- Log into an account with characters across multiple realms
- Open the addons panel and toggle an addon for a character off-realm
- Switch to that character's realm and open the addons panel
- Search for the addon you toggled, observe desync

### Acknowledgements
Meo said to credit him for the hard work of discovering this bug. The only thing he deserves credit for is my descent into madness.

**Comment by kthugs** [comment]
For example, I have 10 characters on one server and a total of 50 characters across 5 servers. Therefore, each server folder in the WTF folder should only contain 10 character folders. However, after running the game and visiting each server once, I find that each server folder contains 50 character folders, resulting in a total of 250 character folders across the 5 server folders.

Even when I select a server with no created characters by clicking “Change Server” in-game, a folder for that server is created in the WTF folder, and 50 character folders are generated within it.

Inside the folders for characters that do not exist on that server, only an Addons.txt file is created. This has caused issues where the addon on/off settings for each character are not saved correctly, and there is significant lag when adjusting the addon list scrollbar.

Since the pre-patch started, this has been bothering me. After quitting the game, I use [Remove-Empty-Directories](https://github.com/hxseven/Remove-Empty-Directories) to delete hundreds of folders that only have addons.txt in them, but when I play the game again, hundreds of folders are created again.

Deleting the addons folder and the WTF folder and doing a "scan and repair" with the Battle.net launcher doesn't help.

**Comment by kthugs** [comment]
Fixed in patch 11.0.5.

Folders with names of characters that do not exist on that server will no longer be created.
