### ISSUE TITLE
icon image error

### ISSUE THREAD

**Issue by Lawmedic** [Stanzilla/WoWUIBugs#674]
<img width="415" alt="화면 캡처 2024-10-18 154415" src="https://github.com/user-attachments/assets/9a946477-ed93-4d50-a890-5991445aa08b">
<img width="406" alt="화면 캡처 2024-10-18 154426" src="https://github.com/user-attachments/assets/5ed18180-e61a-4a97-be58-7e0d1f69a655">

If I insert a spell button with a macro into Button Forge, the first time a character is connected, the place where the spell icon would be placed is “?” appears instead, and the icon appears normally only after opening the macro editing window and re-saving the macro for each order.

**Comment by Lawmedic** [comment]
Uploading 녹음 2024-10-18 155140.mp4…

**Comment by EKE00372** [comment]
This is **not** the Button Forge bug tracker.

If the message from Button Forge curse page linked you here, that descripe at curse page top was just notice users that the reason flyout action bars cannot be used is due to Blizzard's restrictions, and it includes a link to here to explaining the issue.
