### ISSUE TITLE
When the action bar is in the snapped state, reloading will be messed up

### ISSUE THREAD

**Issue by ghost** [Stanzilla/WoWUIBugs#690]
When the action bar is in the snapped state, reloading will be messed up, usually moving to the upper left corner of the screen, and return to normal when switching talents or entering edit mode. The way to reproduce is to snap the top of action bar 1 to the bottom of action bar 2, then re-enter the game

**Comment by ghost** [comment]
Action bar 1 is attached to the action bar above
![微信截图_20241204140803](https://github.com/user-attachments/assets/563cbb3d-6f49-4c54-8166-ac3f1d82f3bc)


Then log in again and it will become like this,
![微信截图_20241204141036](https://github.com/user-attachments/assets/d3477cc1-0c64-4bab-a8ed-8728760f44ae)

**Comment by EKE00372** [comment]
>Bug reports submitted here should - where possible - include a minimal reproducible test case either as an attached addon or an in-line code snippet, and steps to reproduce the issue.

不知道你是怎么找到这里来的，但这里是开发者的 ui bug tracker，不是面向玩家的插件问答区，如何回报问题有其规范，而非语焉不详地配几个图就跑，而且你遇到的问题也**不等于**一定就暴雪的ui bug；要报告编辑模式的问题，首先要确认这**并非因为你自己的操作或是插件冲突导致的，并且可以稳定复现**，接着列出步骤，描述如何**完全清空编辑模式的配置后，新建一个编辑模式配置，再更改哪些布局，就可以复现出此问题**，最后附上你出问题的编辑模式字符串。

就以你这个 issue 来说，只说重现步骤是把两个动作条对齐攘后重进游戏，难道默认布局不是开启粘附的状态下两个对齐？换个方式说，如果重现步骤如此简单，以编辑模式的普及度应该早有人在这个 tracker 报告问题了，所以你遇到的不是普遍性问题，那么如此简略的 issue 将会因为信息不足变成一个无效回报。

最后回到你的问题本身，虽然不多但其他地方 (例如官网论坛) 确实有相关回报，根据过往案例，排除某些插件干扰引起的情况后，如果还有问题，可能是编辑模式配置出了问题，但又没有损坏到完全不可用。

Not sure how you found your way here, but this is the developer’s UI bug tracker, not a general Q&A section for players. Reporting issues follows certain guidelines; you can’t just drop a few vague screenshots and leave. Moreover, the issue you’re experiencing is not necessarily a Blizzard UI bug by default.

If you want to report a problem with Edit Mode, you must first ensure that it’s not caused by your own actions or addon conflicts, and that it can be consistently reproduced. Then, outline the steps needed to recreate the problem, specifically describing how after completely clearing your Edit Mode configuration, creating a new one, and then making certain layout changes, you can reproduce the issue. Finally, attach the Edit Mode configuration string that triggers the problem.

Take your current issue as an example: you only said that the reproduction steps are to align two action bars, log out, and log back in. But isn’t the default layout set to have bars aligned under sticky conditions? Put another way, if it were really that simple, given how widely used edit mode is, someone else would have reported it here before. So what you’re facing isn’t a universal problem, an issue described this vaguely will be considered an invalid bug report.

Finally, returning to the issue itself: although it’s a relatively small-scale problem, there have been reports on other forums, including the official forum. Aside from issues caused by certain addon interferences, this could be due to some underlying problem with the Edit Mode configuration—one that isn’t severe enough to render it completely unusable.

https://bbs.nga.cn/read.php?tid=42492152
https://eu.forums.blizzard.com/en/wow/t/action-bars-keep-jumping-to-the-upper-left-of-screen/402639
https://us.forums.blizzard.com/en/wow/t/my-action-bars-and-layouts-keep-moving/1992503

**Comment by ghost** [comment]
> > 此处提交的错误报告应 - 在可能的情况下 - 包括一个最小可重现的测试用例（作为附加插件或内联代码片段），以及重现问题的步骤。
> 
> 不知道你是怎么找到这里来的，但这里是开发者的 ui bug tracker，不是面向玩家的插件问答区，如何返回问题有其规范，而且语焉不详地配几个图就跑，而且你遇到了的问题**也不**等于就暴雪的ui bug；要编辑报告模式的问题，首先要确认这**不是因为你自己的操作或者插件冲突导致的，并且可以稳定恢复现**，然后加入注册步骤，描述如何**清空编辑模式的配置后，新建一个编辑模式配置，再更改哪些布局，就可以复现出这个问题**，最后附上你出问题的编辑模式字符串。
> 
> 就你这个问题来说，只说重置步骤是把两个动作条像素操完后重进游戏，考虑默认布局不是关闭触摸的状态下两个像素？换个方式说，如果重置步骤这么简单，以编辑模式的普及度应该早有人在这个追踪器报告了问题，所以你遇到了不普遍性的问题，那么如此简略的问题将会因为信息不足变成一个无效返回。
> 
> 最后回到你的问题本身，虽然很少但其他地方（例如官网论坛）确实有相关返回，根据过去的案例，排除某些插件干扰引起的情况后，如果还有问题，可能是编辑模式配置产生的问题，但又没有损坏到完全不可用。
> 
> 不知道你是怎么找到这里的，但这是开发人员的 UI 错误跟踪器，而不是玩家的一般问答部分。报告问题遵循某些准则；你不能只是放几张模糊的截图然后离开。此外，你遇到的问题不一定是暴雪默认的 UI 错误。
> 
> 如果您想报告编辑模式的问题，您必须首先确保该问题不是由您自己的操作或插件冲突引起的，并且可以一致地重现。然后，概述重现问题所需的步骤，具体描述如何在完全清除编辑模式配置、创建新配置，然后进行某些布局更改后重现该问题。最后，附上触发问题的编辑模式配置字符串。
> 
> 以你当前的问题为例：你只说重现步骤是对齐两个操作栏、注销并重新登录。但默认布局不是设置为在棘手条件下对齐操作栏吗？换句话说，如果真的这么简单，考虑到编辑模式的使用范围如此广泛，其他人早就在这里报告了。所以你面临的不是一个普遍性问题，如此模糊描述的问题将被视为无效的错误报告。
> 
> 最后，回到问题本身：虽然这是一个相对小规模的问题，但其他论坛（包括官方论坛）也报告过这个问题。除了某些插件干扰导致的问题外，这可能是由于编辑模式配置的一些潜在问题造成的——这些问题还不足以导致其完全无法使用。
> 
> [https://bbs.nga.cn/read.php?tid=42492152 ](https://bbs.nga.cn/read.php?tid=42492152) [https://eu.forums.blizzard.com/en/wow/t/action-bars-keep-jumping-to-the-upper-left -屏幕外/402639](https://eu.forums.blizzard.com/en/wow/t/action-bars-keep-jumping-to-the-upper-left-of-screen/402639)

好的,明白(能用中文太好了,翻译软件对于一些控件UI我也不知道翻译的对不对,所以有个帖子我把ObjectiveTracker写错了),   中间一个朋友告诉我这里有反馈的BUG之类的, 是我误会了,非常抱歉! 既然如此,我会删除其他几个没必要的帖子.
不过这个BUG是真实存在的. 我反复测试过很多次,  复现的步骤是, 
1, 删除所有的插件  进入编辑模式
2, 随便用一个动作条, 对动作条2进行吸附,吸附哪条边都行,然后保存退出
3,然后/reload 或者退出重新进入游戏, 就会出现了
4.当切换天赋或者重新进入编辑模式后再退出,又会恢复正常


好啦,不好意思打扰到你,我在论坛上搜索发现不止我一个人遇到这个问题, 如果确实没有这个问题或者不值得修复的话,那就请关闭这个问题.打扰啦

**Comment by EKE00372** [comment]
我是根据截图和行文判断用中文和你说明比较能让你理解，不是这个 tracker 可以用中文。

我们应当可以确认这个bug存在，但前面说过，给出的复现步骤太普通，他人不能按此操作复现，信息不完整；单纯回报问题，官网论坛足够了，这个 tracker **并不会**使问题更快修复。

先尝试上面附的三个连结，因为从你的回覆得知，你似乎没有在**完全干净的配置**操作过此复现步骤，所谓完全干净是指，该帐号下的编辑模式配置是空的，彻底重置了配置，没有任何自定义配置，从初次登录开始没有启用过插件，确保编辑模式没有被外部因素干涉过。编辑模式的配置是存在服务器端的，所以被破坏的混乱配置可能会不断被拉取同步。

I’m explaining this to you in Chinese because I thought it might help you understand better. It doesn’t mean this tracker supports Chinese.

Assuming we confirmed this bug definitely exists, the reproduction steps you’ve given are too generic, there must be missing information. so if you just simply reporting an issue, the official forums will suffice.

And the link I provided is a suggestion for you to try out, From your replies, it’s clear that you haven’t tested these reproduction steps under a completely clean configuration.
By “completely clean,” I mean that the edit mode config on that account is empty, no custom edit mode config,  no addons have ever been enabled since the very first login—ensuring that edit mode hasn’t been influenced by any external factors. Since the edit mode configuration is stored at server-side, any corrupted configuration might be continuously retrieved and synchronized.

**Comment by ghost** [comment]
> 我是根据截图和行文判断用中文和你说明比较能让你理解，不是这个 tracker 可以用中文。
> 
> 我们应当可以确认这个bug存在，但前面说过，给出的复现步骤太普通，他人不能按此操作复现，信息不完整；单纯回报问题，官网论坛足够了，这个 tracker **并不会**使问题更快修复。
> 
> 先尝试上面附的三个连结，因为从你的回覆得知，你似乎没有在**完全干净的配置**操作过此复现步骤，所谓完全干净是指，该帐号下的编辑模式配置是空的，彻底重置了配置，没有任何自定义配置，从初次登录开始没有启用过插件，确保编辑模式没有被外部因素干涉过。编辑模式的配置是存在服务器端的，所以被破坏的混乱配置可能会不断被拉取同步。
> 
> I’m explaining this to you in Chinese because I thought it might help you understand better. It doesn’t mean this tracker supports Chinese.
> 
> Assuming we confirmed this bug definitely exists, the reproduction steps you’ve given are too generic, there must be missing information. so if you just simply reporting an issue, the official forums will suffice.
> 
> And the link I provided is a suggestion for you to try out, From your replies, it’s clear that you haven’t tested these reproduction steps under a completely clean configuration. By “completely clean,” I mean that the edit mode config on that account is empty, no custom edit mode config, no addons have ever been enabled since the very first login—ensuring that edit mode hasn’t been influenced by any external factors. Since the edit mode configuration is stored at server-side, any corrupted configuration might be continuously retrieved and synchronized.

If submitting this error here does not help to fix the bug itself, then I'm sorry to bother you. After I canceled the adsorption, this problem no longer bothered me. But in the end I still followed your detailed operation. I have no other intention, I just want to prove that it does exist and it is easy to happen.

To ensure cleanliness this time, I used an account of a friend who had not logged in for many years.
Before entering the game, I deleted WTF, Interface and Cache.
![微信截图_20241205151353](https://github.com/user-attachments/assets/27ab2195-9599-4404-837f-9bea4da430d7)

Then follow the instructions in the link you gave, delete layout-local.txt, layout-local.old,edit-mode-cache-account.txt,edit-mode-cache-account.old,

First, create a new character, then enter the game, check Action Bar 2, Action Bar 3,
Then went into edit mode and made sure there weren't any personal layouts.
![微信截图_20241205151851](https://github.com/user-attachments/assets/252ea0b9-ae1f-4880-81a5-d7cfc123ca05)

Then move action bar 3 down slightly so that it is attached to action bar 2, save it as a new layout, and then exit edit mode.
![微信截图_20241205151915](https://github.com/user-attachments/assets/20eaf9cf-c742-40ea-b3a5-260821b40c9a)

Use /reload to refresh the interface, and action bar 3 will appear in the upper left corner.
![微信截图_20241205151944](https://github.com/user-attachments/assets/8874ab4d-bb55-4c70-9750-35f291ed3ad2)

Finally, I apologize again for the unnecessary interruption. Have a nice day

**Comment by EKE00372** [comment]
如果要保持这个 issue，再补充你游戏的分辨率、ui缩放、全屏还是窗口化，还有编辑模式配置。配置太长可以用折叠或代码语法框起来。最后还是没有复现出来。

Ok if now we keep this issue open, need have more info: your game screen resolution and UI Scale, running game in fullscreen or window mode, your edit mod layout/cache (can post by code block or collapse if you worried it's too long or messy). Finally I regreted still unable to reproduce this issue using your steps.

**Comment by ghost** [comment]
> 如果要保持这个 issue，再补充你游戏的分辨率、ui缩放、全屏还是窗口化，还有编辑模式配置。配置太长可以用折叠或代码语法框起来。最后还是没有复现出来。
> 
> Ok if now we keep this issue open, need have more info: your game screen resolution and UI Scale, running game in fullscreen or window mode, your edit mod layout/cache (can post by code block or collapse if you worried it's too long or messy). Finally I regreted still unable to reproduce this issue using your steps.

game screen resolution: 1920x1080,   No UI scaling is used, Full Screen Gaming, edit mod layout/cache: `1 39 0 0 1 7 7 UIParent 0.0 45.0 -1 ##$$%/&('%)#+#,$ 0 1 1 7 7 UIParent 0.0 45.0 -1 ##$$%/&('%(#,$ 0 2 1 7 7 UIParent 0.0 45.0 -1 ##$$%/&('%(#,$ 0 3 1 5 5 UIParent -5.0 -77.0 -1 #$$$%/&('%(#,$ 0 4 1 5 5 UIParent -5.0 -77.0 -1 #$$$%/&('%(#,$ 0 5 0 0 0 UIParent 0.0 -0.0 -1 ##$$%/&('%(#,$ 0 6 1 1 4 UIParent 0.0 -50.0 -1 ##$$%/&('%(#,$ 0 7 1 1 4 UIParent 0.0 -100.0 -1 ##$$%/&('%(#,$ 0 10 1 7 7 UIParent 0.0 45.0 -1 ##$$&('% 0 11 1 7 7 UIParent 0.0 45.0 -1 ##$$&('%,# 0 12 1 7 7 UIParent 0.0 45.0 -1 ##$$&('% 1 -1 1 4 4 UIParent 0.0 0.0 -1 ##$#%# 2 -1 1 2 2 UIParent 0.0 0.0 -1 ##$#%( 3 0 1 8 7 UIParent -300.0 250.0 -1 $#3# 3 1 1 6 7 UIParent 300.0 250.0 -1 %#3# 3 2 1 6 7 UIParent 520.0 265.0 -1 %#&#3# 3 3 1 0 2 CompactRaidFrameManager 0.0 -7.0 -1 '#(#)#-#.#/#1$3# 3 4 1 0 2 CompactRaidFrameManager 0.0 -5.0 -1 ,#-#.#/#0#1#2( 3 5 1 5 5 UIParent 0.0 0.0 -1 &#*$3# 3 6 1 5 5 UIParent 0.0 0.0 -1 -#.#/#4$ 3 7 1 4 4 UIParent 0.0 0.0 -1 3# 4 -1 1 7 7 UIParent 0.0 45.0 -1 # 5 -1 1 7 7 UIParent 0.0 45.0 -1 # 6 0 1 2 2 UIParent -255.0 -10.0 -1 ##$#%#&.(()( 6 1 1 2 2 UIParent -270.0 -155.0 -1 ##$#%#'+(()( 7 -1 1 7 7 UIParent 0.0 45.0 -1 # 8 -1 0 6 6 UIParent 35.0 50.0 -1 #'$A%$&7 9 -1 1 7 7 UIParent 0.0 45.0 -1 # 10 -1 1 0 0 UIParent 16.0 -116.0 -1 # 11 -1 1 8 8 UIParent -9.0 85.0 -1 # 12 -1 1 2 2 UIParent -110.0 -275.0 -1 #K$#%# 13 -1 1 8 8 MicroButtonAndBagsBar 0.0 0.0 -1 ##$#%)&- 14 -1 1 2 2 MicroButtonAndBagsBar 0.0 10.0 -1 ##$#%( 15 0 1 7 7 StatusTrackingBarManager 0.0 0.0 -1 # 15 1 1 7 7 StatusTrackingBarManager 0.0 17.0 -1 # 16 -1 1 5 5 UIParent 0.0 0.0 -1 #( 17 -1 1 1 1 UIParent 0.0 -100.0 -1 ## 18 -1 1 5 5 UIParent 0.0 0.0 -1 #- 19 -1 1 7 7 UIParent 0.0 0.0 -1 ##`

I uploaded a video to show this bug. Before starting this video, I have deleted WTF, Interface and Cache, layout-local.txt, layout-local.old,edit-mode-cache-account.txt,edit-mode-cache-account.old files, and restored all the settings in the game. This time it must be absolutely clean. In the video, I also showed the problem that the ObjectiveTracker will move upwards after entering the edit mode.
Whether you can reproduce this bug or not, I will close all the questions after receiving the reply. I have realized that this is not the place for me to come. We have wasted a lot of time on these problems, and it may not help to solve it.
Here is the video link:
https://youtu.be/bmynVpuaDWY?feature=shared
