### ISSUE TITLE
Questions about the game Raid framework

### ISSUE THREAD

**Issue by ghost** [Stanzilla/WoWUIBugs#694]
I can't set up separate configurations for different talents and different team sizes, which I could do before. And the font size is a bit too large in the default five-player team frame. In short, I still hope to be able to adjust the team interface more freely and have more customization options.

**Comment by EKE00372** [comment]
这不是规范的回报方式，回报问题不是闲聊，请条列清楚需求，内容重点是功能而不是你自己如何如何，标题应该写明 feature request。

This is not the proper way request feature here. Reporting problems isn’t a casual conversation. Please list your requirements clearly, focusing on the requested functionality rather than yourself what how. The title should explicitly indicate it’s a feature request.

summarize:

Feature request: more raidframe options in game
* Allow player create different raidframe profiles based on spec and group size. This feature got removed ever since editmode was introduced in Dragonflight.
* More size-related settings. Large, high-resolution screens are becoming increasingly common, the raidframe size adjustment range in option is too limited, additionally, adjusting the size of aura icons completely depends on addons.
