### ISSUE TITLE
TaxiFrame:Show() crashes the TBC client

### ISSUE THREAD

**Issue by DDCorkum** [Stanzilla/WoWUIBugs#99]
**Issue:** Calling `TaxiFrame:Show()` crashes the TBC client

**Expected result:** Classic and Retail trigger ERR_TAXINOPATHS

**Alternative ways to reproduce:** 
- /run in the chat window
- First line of an addon
- Added to the macrotext property of a Button inheriting SecureActionButtonTemplate, and then clicking it in-game.

**Impact to users:**  Minor/negligible.  Who would ever do this on a live server?

**Comment by DDCorkum** [comment]
Update:  Turns out to be caught by an assert, and related to textures, and apparently happens on PTR also.  So this could probably be closed.

ERROR #0 (0x85100000) Assertion failure!
Texture.cpp, line 2891, expression "fileID != 0"
Line: 2891
Expr: fileID != 0

**Comment by Meorawr** [comment]
A more compact way to reproduce the assertion is to run the following after logging in without visiting a taxi service:

```lua
/run SetTaxiMap(PlayerPortrait)
```

As it doesn't affect assertions-disabled builds I'll keep this open under the PTR/TBC label so it can be logged at least - if we don't hear back on this one or it doesn't seem to get fixed by the end of the beta/ptr cycle then we can close it as a probably-wontfix.

**Comment by Meorawr** [comment]
Just for context on why this was closed, as assertions are already submitted via the client error reporter and Blizzards' tooling is better at recording them we'll not put assertions or other client crash tickets here unless they're actually significantly likely enough for people to run into.
